config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:show]
    resources :categories, only: [:show]
    resources :carts, only: [:index, :create, :update, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/product_decorator.rb
module Spree::ProductDecorator
  def self.prepended(base)
    base.class_eval do
      scope :filter_by_option_value, -> (option_value) {
        return if option_value.blank?
        joins(variants: :option_values).where(spree_option_values: { name: option_value }).distinct
      }

      scope :with_sort_product, -> (sort) {
        if sort == "NEW_PRODUCTS"
          order(available_on: :desc)
        elsif sort == "OLD_PRODUCTS"
          order(available_on: :asc)
        elsif sort == "HIGH_PRICE"
          descend_by_master_price
        elsif sort == "LOW_PRICE"
          ascend_by_master_price
        end
      }

      scope :with_new_release_products, -> (max_length) {
        available.includes(master: [:default_price, :images]).order(available_on: "DESC").limit(max_length)
      }
    end
  end

  def related_products(max_length)
    Spree::Product.in_taxons(taxons).
      includes(master: [:images, :default_price]).
      where.not(id: id).distinct.sample(max_length)
  end

  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/carts_controller.rb
class Potepan::CartsController < ApplicationController
  protect_from_forgery
  before_action :store_guest_token, except: [:destroy]
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def index
    @order = Spree::Order.incomplete.find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def create
    @order = current_order(create_order_if_necessary: true)
    authorize! :update, @order, cookies.signed[:guest_token]

    variant  = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].present? ? params[:quantity].to_i : 1

    if !quantity.between?(1, 2_147_483_647)
      @order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = @order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => error
      @order.errors.add(:base, error.record.errors.full_messages.join(", "))
    end

    if @order.errors.any?
      flash[:error] = @order.errors.full_messages.join(", ")
      redirect_to potepan_carts_path
    else
      redirect_to potepan_carts_path
    end
  end

  def update
    @order = Spree::Order.find(params[:id])
    @order.contents.update_cart(order_params)
    redirect_to potepan_carts_path
  end

  def destroy
    @line_item = Spree::LineItem.find(params[:id])
    @line_item.order.contents.remove_line_item(@line_item)
    redirect_to potepan_carts_path
  end

  private

  def store_guest_token
    cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
  end

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity, :price])
  end
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :count_option_value_products

  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(root: :children)
    @color_categories = Spree::OptionType.find_by(presentation: "Color").option_values
    @size_categories = Spree::OptionType.find_by(presentation: "Size").option_values
    @products = @taxon.all_products.includes(master: [:default_price, :images]).
      where.not("available_on > :available_on", { available_on: Time.current }).
      filter_by_option_value(params[:color]).
      filter_by_option_value(params[:size]).
      with_sort_product(params[:sort])
  end

  def count_option_value_products(option_value)
    @taxon.all_products.includes(variants: :option_values).where(spree_option_values: { name: option_value }).count
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_LENGTH_RELATED_PRODUCTS = 4
  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products(MAX_LENGTH_RELATED_PRODUCTS)
    @variants = @product.variants.includes(:option_values)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  MAX_NEW_PRODUCTS = 6
  def index
    @products = Spree::Product.with_new_release_products(MAX_NEW_PRODUCTS)
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = nil)
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end

  def url_with_params(url, params = {})
    uri = URI.parse(url)
    uri.query = URI.encode_www_form(params.to_a)
    uri.to_s
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_login.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-main navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/potepan/"><%= image_tag("img/logo.png", :alt => "") %></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to "Home",potepan_path %></li>
        <li class="dropdown megaDropMenu">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_signup.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_topbar.html.erb
<div class="topBar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 hidden-sm hidden-xs">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
      <div class="col-md-6 col-xs-12">
        <ul class="list-inline pull-right">
          <li class="dropdown searchBox">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <form id="form01" action="product-grid-left-sidebar.html" method="post">
                <li>
                  <span class="input-group">
                    <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                  </span>
                </li>
              </form>
            </ul>
          </li>
          <li class="dropdown">
            <%= link_to(potepan_carts_path, class: "dropdown-toggle") do %>
              <i class="fa fa-shopping-cart"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- PLUGINS CSS STYLE -->
    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
    <!-- CUSTOM CSS -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <%= render 'layouts/shim' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>
    <!-- HEADER -->
    <div class="header clearfix">
      <!-- TOPBAR -->
      <%= render 'layouts/topbar' %>
      <!-- NAVBAR -->
      <%= render 'layouts/navbar' %>
    </div>
    <%= yield %>
    <%= javascript_include_tag('application') %>
  </body>
  <footer>
    <!-- FOOTER -->
    <%= render 'layouts/footer' %>
    <!-- LOGIN MODAL -->
    <%= render 'layouts/login' %>
    <!-- SIGN UP MODAL -->
    <%= render 'layouts/signup' %>
  </footer>
</html>

app/views/potepan/carts/_cart_header.html.erb
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <%= link_to "Home",potepan_path %>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/carts/_form.html.erb
<%= form_with(model: order, url: potepan_cart_path(order.id), method: :patch, local: true) do |f| %>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>商品名</th>
          <th>価格</th>
          <th>数</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'line_items', collection: order.line_items, as: :line_item, locals: {f: f} %>
      </tbody>
    </table>
  </div>
  <div class="updateArea">
    <%= f.submit 'アップデート', :class=>"btn" %>
  </div>
<% end %>

app/views/potepan/carts/_line_items.html.erb
<tr>
  <td class="col-xs-2">
    <%= link_to(potepan_cart_path(line_item.id), method: :delete, class: "close") do %>
      <span aria-hidden="true">&times;</span>
    <% end %>
    <span class="cartImage"><%= image_tag(line_item.variant.display_image.attachment(:product)) %></span>
  </td>
  <td class="col-xs-4"><%= line_item.name %></td>
  <td class="col-xs-2"><%= line_item.price %></td>
  <%= f.fields_for :line_items, line_item do |item_form| %>
    <td class="col-xs-2"><%= item_form.number_field :quantity, min:0 %></td>
  <% end %>
  <td class="col-xs-2"><%= line_item.amount %></td>
</tr>

app/views/potepan/carts/index.html.erb
<!DOCTYPE html>
<!-- LIGHT SECTION -->
<%= render 'cart_header' %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <% if @order.line_items.empty? %>
            <p>カートは空です。</p>
          <% else %>
            <%= render 'form', order: @order %>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span><%= @order.display_item_total %></span></li>
                  <li>消費税 <span><%= @order.display_tax_total %></span></li>
                  <li>総計 <span class="grandTotal"><%= @order.display_total %></span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_category_header.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_color.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <% colors.each do |color| %>
      <ul class="list-unstyled">
  	    <li>
  	      <%= link_to url_with_params(potepan_category_path(taxon.id), {color: color.name}) do %>
    		    <%= color.presentation %><span>(<%= count_option_value_products(color.name) %>)</span>
  	      <% end %>
  	    </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_filter_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <%= form_tag request.url, method: :get do %>
      <%= select_tag "sort", options_for_select([
        ["新着順","NEW_PRODUCTS"],
        ["古い順","OLD_PRODUCTS"],
        ["高い順","HIGH_PRICE"],
        ["安い順","LOW_PRICE"]],
        selected: params[:sort]), {id: "guiest_id1", class: "select-drop", onChange: "this.form.submit()"} %>
    <% end %>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_product.html.erb
<div class="col-sm-4 col-xs-12">
  <%= link_to potepan_product_path(product.id) do %> 
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment(:small)) %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/categories/_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
  	<% sizes.each do |size| %>
	  <ul class="list-unstyled clearfix"> 
	    <li>
	      <%= link_to url_with_params(potepan_category_path(taxon.id), {size: size.name}) do %>
		    <%= size.presentation %><span>(<%= count_option_value_products(size.name) %>)</span>
		  <% end %>
	    </li>
	  </ul>
    <% end %>
  </div>
</div>

app/views/potepan/categories/_taxonomies.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each do |taxonomy| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#category-<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
            <ul id="category-<%= taxonomy.id %>" class="collapse collapseItem">
              <% taxonomy.root.leaves.each do |taxon| %>
                <li>
                  <%= link_to potepan_category_path(taxon.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %><span>(<%= taxon.products.count %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/products/_cart.html.erb
<%= form_for :order, url: potepan_carts_path, method: :post, local: true do |f| %>
  <div class="media-body">
    <ul class="list-inline">
      <li>
        <%= link_to potepan_category_path(product.taxons.first.id) do %>
          <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る
        <% end %>
      </li>
    </ul>
    <h2><%= product.name %></h2>
    <h3><%= product.display_price %></h3>
    <p><%= product.description %></p>
    <!-- Cart Section -->
    <% if variants.any? %>
      <span class="quick-drop">
        <%= f.select :variant_id,
          variants.map{|variant|
            ["Size:#{variant.option_values.first.presentation},Color:#{variant.option_values.second.presentation}",variant.id]},{}, {id: "variant_id", name:"variant_id", class: "select-drop"} %>
      </span>
      <% else %>
        <%= hidden_field_tag "variant_id", product.master.id %>
    <% end %>
    <span class="quick-drop resizeWidth">
      <%= f.select :quantity,[
        ["1",1],
        ["2",2],
        ["3",3],
        ["4",4],
        ["5",5]],
      {},{name: "guiest_id4", id: "guiest_id4", class: "select-drop"} %>
      </select>
    </span>
    <div class="btn-area">
      <%= f.submit "カートへ入れる", :class=>"btn btn-primary btn-block" %><i class="fa fa-angle-right" aria-hidden="true"></i>
    </div>
  </div>
<% end %>

app/views/potepan/products/_product_header.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home",potepan_path %>
          </li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/sample/cart_page.html.erb
<!DOCTYPE html>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <%= link_to "Home",potepan_path %>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <form action="#">
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                  <tr>
                    <td class="col-xs-2">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <span class="cartImage"><%= image_tag("img/products/cart-image.jpg", :alt => "image") %></span>
                    </td>
                    <td class="col-xs-4">Italian Winter Hat</td>
                    <td class="col-xs-2">99円</td>
                    <td class="col-xs-2"><input type="text" placeholder="1"></td>
                    <td class="col-xs-2">99円</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
              <a href="#" class="btn">アップデート</a>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span>792円</span></li>
                  <li>消費税 <span>18円</span></li>
                  <li>総計 <span class="grandTotal">810円</span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="checkout_step_1.html" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/share/_new_products.html.erb
<div class="row featuredProducts">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>新着商品</h4>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="owl-carousel featuredProductsSlider">
      <% products.each do |product| %>
        <%= link_to potepan_product_path(product.id) do %>
          <div class="slide">
            <div class="productImage clearfix">
              <%= image_tag(product.display_image.attachment(:product)) %>
            </div>
            <div class="productCaption clearfix">
              <h5><%= product.name %></h5>
              <h3><%= product.display_price %></h3>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/potepan/share/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <%= link_to potepan_product_path(related_product.id) do %> 
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment(:product)) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= related_product.name %></h5>
            <h3><%= related_product.display_price %></h3>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>